# Generated by Django 5.0.3 on 2024-03-31 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Radio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("path", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "quality",
                    models.CharField(
                        choices=[("l", "low"), ("m", "medium"), ("h", "high")],
                        max_length=1,
                    ),
                ),
                ("tags", models.ManyToManyField(to="media.tag")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("path", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("file_size", models.IntegerField(default=0)),
                ("md5_hex", models.CharField(max_length=200, unique=True)),
                ("duration", models.DurationField(default=datetime.timedelta(0))),
                ("tags", models.ManyToManyField(to="media.tag")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("path", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("file_size", models.IntegerField(default=0)),
                ("md5_hex", models.CharField(max_length=200, unique=True)),
                ("duration", models.DurationField(default=datetime.timedelta(0))),
                ("tags", models.ManyToManyField(to="media.tag")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
