# Generated by Django 5.0.3 on 2024-03-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="path",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="radio",
            name="path",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="path",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
