# Generated by Django 5.0.3 on 2024-09-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_audio_path_alter_radio_path_alter_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radio',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
