# Generated by Django 5.2 on 2026-05-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_audio_play_count_radio_play_count_video_play_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='authors',
            field=models.ManyToManyField(to='media.author'),
        ),
    ]
