# Generated by Django 5.2 on 2026-05-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_author_audio_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
