# Generated by Django 5.2 on 2026-05-11 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_tagfilterpreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagfilterpreset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tagfilterpreset',
            name='media_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('radio', 'Radio'), ('video', 'Video')], default='audio', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tagfilterpreset',
            unique_together={('name', 'user', 'media_type')},
        ),
    ]
